### ISSUE TITLE
在编译完成后，运行开始时跳出exited

### ISSUE THREAD

**Issue by wsxccc** [vvbbnn00/WARP-Clash-API#1]
warp-clash-api-warp-clash-1 exited with code 127
warp-clash-api-warp-clash-1  | 2023-10-22T06:56:40.940651810Z ./scripts/run.sh: line 2:: not found
: not found14:56:40 warp-clash-api-warp-clash-1  | ./scripts/run.sh: line 4: 
: not found14:56:40 warp-clash-api-warp-clash-1  | ./scripts/run.sh: line 5: 
2023-10-22 14:56:40 warp-clash-api-warp-clash-1  | usage: app.py [-h] {web,background,optimize}
2023-10-22 14:56:40 warp-clash-api-warp-clash-1  | app.py: error: argument command: invalid choice: 'web\r' (choose from 'web', 'background', 'optimize')
: not found14:56:40 warp-clash-api-warp-clash-1  | ./scripts/run.sh: line 7:

**Comment by vvbbnn00** [comment]
你好，相关问题已定位，请尝试使用最新的代码，查看问题是否修复，谢谢。

Hello, the relevant issue has been identified. Please try pulling the latest code to see if the problem has been fixed. Thank you.

**Comment by wsxccc** [comment]
感谢修复，程序已正常运行，不过似乎手动优选ip无法正常运行，以下是log：
/app # python3 app.py optimize
./scripts/get_entrypoints.sh: line 3: $'\r': command not found
./scripts/get_entrypoints.sh: line 4: $'\r': command not found
./scripts/get_entrypoints.sh: line 5: syntax error near unexpected token `$'{\r''
'/scripts/get_entrypoints.sh: line 5: `archAffix(){

**Comment by vvbbnn00** [comment]
你好，这可能是因为文件`get_entrypoints.sh`的换行符格式为CRLF导致的。现已修复，请尝试使用最新的代码，谢谢！

Hello, this issue might have been caused by the file `get_entrypoints.sh` having the CRLF line ending format. It has now been fixed. Please try using the latest code. Thank you!

**Comment by wsxccc** [comment]
> 你好，这可能是因为文件`get_entrypoints.sh`的换行符格式为CRLF导致的。现已修复，请尝试使用最新的代码，谢谢！
> 
> Hello, this issue might have been caused by the file `get_entrypoints.sh` having the CRLF line ending format. It has now been fixed. Please try using the latest code. Thank you!

你好，手动优选ip还是无法正常启用，log与上次相同，也许是我弄错了项目目录的含义。

**Comment by vvbbnn00** [comment]
你好，经过检查，我发现在`Windows`系统下`clone`仓库时，默认情况下，换行符为`LF`的文件会被自动转换为`CRLF`。具体可以参考这篇文章：https://www.zhihu.com/question/50862500
然而，我们需要执行`docker compose`，编译镜像后在`docker`环境中执行。但其中的`.sh`文件实际上是`CRLF`格式的，这正是导致上述问题的原因。
为了解决这个问题，你可以在IDE的右下角找到并修改`get_entrypoints.sh`和`run.sh`为`LF`格式，或者，也可以在`Linux`系统中使用`dos2unix`工具。
希望这些建议对你有帮助，谢谢。

Hello, after checking, I found that when cloning a repository on the `Windows system`, by default, files with line endings of `LF` are automatically converted to `CRLF`. For more details, you can refer to this article: https://www.zhihu.com/question/50862500
However, we need to execute `docker compose`, compile the image, and then run it in the docker environment. Yet, the `.sh` files within are in `CRLF` format, which is the root cause of the aforementioned issue.
To solve this problem, you can try locating and modifying `get_entrypoints.sh` and `run.sh` to `LF` format in the bottom right corner of your IDE, or use the `dos2unix` tool on a `Linux` system.
I hope these suggestions are helpful to you. Thank you.

**Comment by wsxccc** [comment]
> 你好，经过检查，我发现在`Windows`系统下`clone`仓库时，默认情况下，换行符为`LF`的文件会被自动转换为`CRLF`。具体可以参考这篇文章：https://www.zhihu.com/question/50862500 然而，我们需要执行`docker compose`，编译镜像后在`docker`环境中执行。但其中的`.sh`文件实际上是`CRLF`格式的，这正是导致上述问题的原因。 为了解决这个问题，你可以在IDE的右下角找到并修改`get_entrypoints.sh`和`run.sh`为`LF`格式，或者，也可以在`Linux`系统中使用`dos2unix`工具。 希望这些建议对你有帮助，谢谢。
> 
> Hello, after checking, I found that when cloning a repository on the `Windows system`, by default, files with line endings of `LF` are automatically converted to `CRLF`. For more details, you can refer to this article: https://www.zhihu.com/question/50862500 However, we need to execute `docker compose`, compile the image, and then run it in the docker environment. Yet, the `.sh` files within are in `CRLF` format, which is the root cause of the aforementioned issue. To solve this problem, you can try locating and modifying `get_entrypoints.sh` and `run.sh` to `LF` format in the bottom right corner of your IDE, or use the `dos2unix` tool on a `Linux` system. I hope these suggestions are helpful to you. Thank you.

你好，感谢您的提醒，手动优选ip程序已正常运行，还有一些问题比如节点间歇性全红有什么好的方法解决吗？

**Comment by vvbbnn00** [comment]
这个可能和您所在的网络环境、或者是您使用的代理软件有关（例如，`shadowrocket`的`wireguard`性能表现就比较糟糕）。很遗憾，该问题暂时可能没有很好的解决方案。

This issue might be related to your network environment or the proxy software you are using (for example, the performance of `wireguard` in `shadowrocket` is quite poor). Unfortunately, there may not be a good solution to this problem at the moment.
